---
# Install packages that every server should have.

- name: Install common packages
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present

- name: Create message of the day
  ansible.builtin.copy:
    dest: /etc/motd
    content: |
      ************************************
      Managed by Ansible
      Owner: {{ owner_name }}
      Host: {{ inventory_hostname }}
      OS: {{ ansible_facts['distribution'] }}
      ************************************
