---
# Tasks execute in order from top to bottom.
#
# Ansible modules are idempotent, meaning they only make
# changes when required to reach the desired state.
# Ensure nginx is installed.
#
# update_cache=true is similar to running:
#   sudo apt update
#
# state=present means:
#   "Install if missing"

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Ensure nginx is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Deploy homepage template
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart nginx
